server:
  port: 8082
  session-timeout: 30
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
     #本地库
     xitongku: 
#       url: jdbc:mysql://101.205.232.195:9486/count?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
#       driverClassName: com.mysql.jdbc.Driver
#       username: root
#       password: 123456
       url: jdbc:oracle:thin:@80.2.20.162:1521/ORCL
       driver-class-name: oracle.jdbc.driver.OracleDriver
       username: jw2ga
       password: jw2ga
       #监控统计拦截的filters
       filters: stat
       #配置初始化大小/最小/最大
       initialSize: 1
       minIdle: 1
       maxActive: 20
       #获取连接等待超时时间
       maxWait: 60000
       #间隔多久进行一次检测，检测需要关闭的空闲连接
       timeBetweenEvictionRunsMillis: 60000
       #一个连接在池中最小生存的时间
       minEvictableIdleTimeMillis: 300000
       validationQuery: SELECT 1 FROM DUAL
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
       poolPreparedStatements: true
       maxPoolPreparedStatementPerConnectionSize: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    # Redis数据库索引（默认为0）
    database: 1 
    host: localhost
 #   port: 6379
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0      # 连接池中的最小空闲连接 默认 0
        max-idle: 8      # 连接池中的最大空闲连接 默认 8
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1ms   # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
mybatis:
  type-aliases-package: com.boot.security.server.system.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
token:
  expire:
    seconds: 7200
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)
files:
  path: ${file-path:d:/files}
logging:
  config: classpath:logback-spring.xml
log:
  level:
    root: info
    my: debug
  file: logs/admin-server.log
  maxsize: 30MB