server:
  port: 5001
spring:
  application:
    name: springcloud-zuul
eureka: 
 instance:
   instance-id: fatherProject-zuul #入住名称
   prefer-ip-address: true #访问路径可以显示ip
 client:  
   service-url: 
     #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机
    defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7001.com:7001/eureka/
zuul:
  ignored-services: fatherproject-dept  #使用routes定义的路由代理，有时候有两个访问路径，这个配置就是将原路径禁止掉
  routes:
#标识你服务的名字，这里可以自己定义，一般方便和规范来讲还是跟自己服务的名字一样
    fatherproject-dept:
#服务映射的路径，通过这路径就可以从外部访问你的服务了，目的是为了不爆露你机器的IP，面向服务的路由了，给你选一个可用的出来，
#这里zuul是自动依赖hystrix，ribbon的，不是面向单机
      path: /dep/**
info: 
  app.name: api网关
  company.name: www.lihao.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$     
    
    
    
    