spring:  
  profiles:
    #开发环境  
    active:
    - dev
spring:  
  profiles: dev
  application: 
    name: dev  
---
spring:  
  profiles: test
  application: 
    name: test  
---
spring:  
  profiles: prod
  application: 
    name: prod  